version: '3'

services:
  client-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Открываем порт 80 контейнера для доступа к фронтенду
    restart: always

  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    restart: always
    volumes:
      - "D:/Develop/Javascript/image-thresh:/app/web-server/image-thresh"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Shurikgat2704
      - PROCESS_IMAGE_URL=host.docker.internal:6001
      - ORIG_IMAGE_PATH=image-fresh/OriginalImages
      - PROCESS_IMAGE_PATH=image-fresh/ProcessedImages